### ISSUE TITLE
Crash with v1.0.12.0

### ISSUE THREAD

**Issue by macklinb** [AltimorTASDK/MGSV-TPP-FoV#2]
Causes mgsvtpp.exe to crash at the intro logos as of the mid-august update, where it was previously working flawlessly.

**Comment by powerbuoy** [comment]
Having the same issue unfortunately :/ Can't go back to the default claustrophobia now...

**Comment by Gnates** [comment]
Same here. Game crashes after the intro logos (Konami, Nvidia etc).

**Comment by mon** [comment]
Found the root cause: int3 padding behind the fov interp function is now 11 bytes, but you need 12 for your trampoline. It nukes the previous function's `ret` and stuff goes kaboom.

I'm not well versed in x64 asm, but I'll go poking and see if I can find a solution.

**Comment by mon** [comment]
While I wait for my pull request to be accepted and an official build, here is a fixed dll. Install like the previous - place in MGS_TPP directory next to the executable.
[fov_fixed.zip](https://github.com/AltimorTASDK/MGSV-TPP-FoV/files/1309103/fov_fixed.zip)

**Comment by powerbuoy** [comment]
Awesome work! Will try this out asap
